#include <TetraParameters.h>

namespace Tetra {

Parameter tetraParameters[] = {
  OscillatorFrequency("OSC 1 FREQ", 0),
  OscillatorFineTune("OSC 1 FREQ FINE", 1),
  OscillatorShape("OSC 1 SHAPE", 2),
  Amount("GLIDE 1", 3),
  OnOff("OSC 1 KEY", 4),
  Amount("SUB OSC 1 LVL", 114),
  OscillatorFrequency("OSC 2 FREQ", 5),
  OscillatorFineTune("OSC 2 FREQ FINE", 6),
  OscillatorShape("OSC 2 SHAPE", 7),
  Amount("GLIDE 2", 8),
  OnOff("OSC 2 KEY", 9),
  Amount("SUB OSC 2 LVL", 115),
  OnOff("SYNC", 10),
  GlideMode("GLIDE MODE", 11),
  OscillatorSlop("OSC SLOP", 12),
  PitchBendRange("PBEND RANGE", 93),
  OscillatorMix("OSC MIX", 13),
  Amount("NOISE LEVEL", 14),
  Amount("FEEDBACK VOL", 116),
  Amount("FEEDBACK GAIN", 110),
  FilterFrequency("FILTER FREQ", 15),
  Amount("RESONANCE", 16),
  Amount("FIL KEY AMT", 17),
  Amount("FIL AUDIO MOD", 18),
  FilterPoles("FILTER POLES", 19),
  PosNegAmount("FILTER ENV AMT", 20),
  Amount("FIL ENV VEL AMT", 21),
  Amount("FIL DEL", 22),
  Amount("FIL ATT", 23),
  Amount("FIL DEC", 24),
  Amount("FIL SUS", 25),
  Amount("FIL REL", 26),
  Amount("VCA LEVEL", 27),
  Amount("VCA ENV AMOUNT", 30),
  Amount("VCA ENV VEL AMT", 31),
  Amount("VCA DEL", 32),
  Amount("VCA ATT", 33),
  Amount("VCA DEC", 34),
  Amount("VCA SUS", 35),
  Amount("VCA REL", 36),
  Amount("OUTPUT PAN", 28),
  Amount("PRESET VOLUME", 29),
  LFOFrequency("LFO 1 FREQ", 37),
  LFOShape("LFO 1 SHAPE", 38),
  Amount("LFO 1 AMT", 39),
  ModulationDestination("LFO 1 DEST", 40),
  OnOff("LFO 1 SYNC", 41),
  LFOFrequency("LFO 2 FREQ", 42),
  LFOShape("LFO 2 SHAPE", 43),
  Amount("LFO 2 AMT", 44),
  ModulationDestination("LFO 2 DEST", 45),
  OnOff("LFO 2 SYNC", 46),
  LFOFrequency("LFO 3 FREQ", 47),
  LFOShape("LFO 3 SHAPE", 48),
  Amount("LFO 3 AMT", 49),
  ModulationDestination("LFO 3 DEST", 50),
  OnOff("LFO 3 SYNC", 51),
  LFOFrequency("LFO 4 FREQ", 52),
  LFOShape("LFO 4 SHAPE", 53),
  Amount("LFO 4 AMT", 54),
  ModulationDestination("LFO 4 DEST", 55),
  OnOff("LFO 4 SYNC", 56),
  ModulationDestination("ENV3 DEST", 57),
  PosNegAmount("ENV3 AMT", 58),
  Amount("ENV 3 VEL AMT", 59),
  Amount("ENV 3 DELAY", 60),
  Amount("ENV3 ATT", 61),
  Amount("ENV3 DEC", 62),
  Amount("ENV3 SUS", 63),
  Amount("ENV3 REL", 64),
  OnOff("ENV3 REPEAT", 98),
  ModulationSource("MOD SOURCE 1", 65),
  PosNegAmount("MOD AMT 1", 66),
  ModulationDestination("MOD DEST 1", 67),
  ModulationSource("MOD SOURCE 2", 68),
  PosNegAmount("MOD AMT 2", 69),
  ModulationDestination("MOD DEST 2", 70),
  ModulationSource("MOD SOURCE 3", 71),
  PosNegAmount("MOD AMT 3", 72),
  ModulationDestination("MOD DEST 3", 73),
  ModulationSource("MOD SOURCE 4", 74),
  PosNegAmount("MOD AMT 4", 75),
  ModulationDestination("MOD DEST 4", 76),
  PosNegAmount("MOD WHEEL AMT", 81),
  ModulationDestination("MOD WHEEL DEST", 82),
  PosNegAmount("PRESSURE AMT", 83),
  ModulationDestination("PRESSURE DEST", 84),
  PosNegAmount("BREATH AMT", 85),
  ModulationDestination("BREATH DEST", 86),
  PosNegAmount("VELOCITY AMT", 87),
  ModulationDestination("VELOCITY DEST", 88),
  PosNegAmount("FOOT AMT", 89),
  ModulationDestination("FOOT DEST", 90),
  UnisonMode("UNISON MODE", 96),
  KeyMode("UNISON ASSIGN", 95),
  OnOff("UNISON ON OFF", 99),
  OscillatorFrequency("PUSH IT NOTE", 111),
  Amount("PUSH IT VEL", 112),
  PushItMode("PUSH IT MODE", 113),
  OscillatorFrequency("KBD SPLIT POINT", 118),
  KeyboardMode("KBD MODE", 119),
  Tempo("TEMPO", 91),
  ClockDivide("TIME SIG", 92),
  ArpeggiatorMode("ARP MODE", 97),
  OnOff("ARP ON OFF", 100),
  SequencerTrigger("SEQ TRIGGER", 94),
  OnOff("SEQ ON OFF", 101),
  ModulationDestination("SEQ 1 DEST", 77),
  ModulationDestination("SEQ 2 DEST", 78),
  ModulationDestination("SEQ 3 DEST", 79),
  ModulationDestination("SEQ 4 DEST", 80),
  ParameterNumber("PARAM ENC SEL V1", 105),
  ParameterNumber("PARAM ENC SEL V2", 106),
  ParameterNumber("PARAM ENC SEL V3", 107),
  ParameterNumber("PARAM ENC SEL V4", 108)
};

};
